spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: embedded
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath:person.sql

logging.level:
  org.hibernate.SQL: debug